/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cplusplus_NativeCalls */

#ifndef _Included_cplusplus_NativeCalls
#define _Included_cplusplus_NativeCalls
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cplusplus_NativeCalls
 * Method:    deleteFile
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_cplusplus_NativeCalls_deleteFile
  (JNIEnv *, jclass, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
