namespace Course_project.Controller
{
	using System;
	public enum CommandType
	{
		ADD_PRIVATE_TASK,
		UPDATE_GROUPS,
		UPDATE_TASK,
		ADD_SHARE_TASK,
		LOGIN,
		REGISTRATION,
		GET_TASKS_FROM_RANGE,
		IMPORT_TO_OUTLOOK,
		ADD_FLEXIBLE_TASK_IN_STORE,
		GET_USER_GROUPS,
		GET_TIME_SPENT_BY_GROUP,
		REMOVE_TASK,
		APPORTION_FLEXIBLE_TASKS
	}
}